## PageRank

In [1]:
%pylab notebook
import numpy as np
import numpy.linalg as la

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
df = np.array([[0,   1/2, 1/3, 0, 0,   0   ],
              [1/3, 0,   0,   0, 1/2, 0   ],
              [1/3, 1/2, 0,   1, 0,   1/2 ],
              [1/3, 0,   1/3, 0, 1/2, 1/2 ],
              [0,   0,   0,   0, 0,   0   ],
              [0,   0,   1/3, 0, 0,   0   ]])

In [3]:
eVals, eVecs = la.eig(df) 
order = np.absolute(eVals).argsort()[::-1] 
eVals = eVals[order]
eVecs = eVecs[:,order]

df1 = eVecs[:, 0] 
100 * np.real(df1 / np.sum(df1))

array([0.96, 0.32, 2.4 , 1.52, 0.  , 0.8 ])

In [4]:
df1 = 100 * np.ones(6) / 6 
df1


array([16.66666667, 16.66666667, 16.66666667, 16.66666667, 16.66666667,
       16.66666667])

In [5]:
df1 = df @ df1 
df1

array([13.88888889, 13.88888889, 38.88888889, 27.77777778,  0.        ,
        5.55555556])