## PageRank

In [31]:
%pylab notebook
import numpy as np
import numpy.linalg as la

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [32]:
df = np.array([[0,   0, 0, 0, 0,   0 ,0 , 0 ,0  ],
              [1/2, 0,   0,   0, 0, 0  ,0,  0, 0 ],
              [0, 0, 0,   0, 0,  0 ,0,  0, 1],
              [1/2, 1/2,   1/2, 0, 1/2, 1/2,1/2,  1/2, 0 ],
              [0,   0,   0,   0, 0,   0 ,0,   1/2, 0  ],
              [0,   0,   0, 0, 0,   0,  0,  0, 0   ],
              [0,   0,   0, 0, 0,   0,  0,  0, 0   ],
              [0,   0,   0, 0, 0,   0,  0,  0, 0   ],
              [0,   0,   0, 0, 0,   0,  0,  0, 0   ],
              
              ])

In [33]:
eVals, eVecs = la.eig(df) 
order = np.absolute(eVals).argsort()[::-1] 
eVals = eVals[order]
eVecs = eVecs[:,order]

df1 = eVecs[:, 0] 
100 * np.real(df1 / np.sum(df1))

array([ 0.00000000e+000,  0.00000000e+000, -1.80375152e-289,
        1.00000000e+002,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000])

In [34]:
df1 = 100 * np.ones(9) / 9
df1


array([11.11111111, 11.11111111, 11.11111111, 11.11111111, 11.11111111,
       11.11111111, 11.11111111, 11.11111111, 11.11111111])

In [35]:
df1 = df @ df1 
df1

array([ 0.        ,  5.55555556, 11.11111111, 38.88888889,  5.55555556,
        0.        ,  0.        ,  0.        ,  0.        ])

In [36]:
#trying convergence

df1_old=df1
df1= df @ df1

i=0
while la.norm(df1_old - df1)>0.01:
    df1_old=df1
    df1= df @ df1
    i=i+1
  
print("number of convergences")
i 


number of convergences


2

In [37]:
b=0.5

m= b* df +(1-b)/9 * np.ones([9,9]) 
m

AttributeError: module 'numpy' has no attribute 'one'