## PageRank

In [3]:
%pylab notebook
import numpy as np
import numpy.linalg as la

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [4]:
df = np.array([[0,   0, 0, 0, 0,   0 ,0 , 0 ,0  ],
              [1, 0,   0,   0, 0, 0  ,0,  0, 0 ],
              [0, 0, 0,   0, 0,  0 ,0,  0, 1],
              [1, 1,   1, 0, 1, 1,1,  1, 0 ],
              [0,   0,   0,   0, 0,   0 ,0,   1, 0  ],
              [0,   0,   0, 0, 0,   0,  0,  0, 0   ],
              [0,   0,   0, 0, 0,   0,  0,  0, 0   ],
              [0,   0,   0, 0, 0,   0,  0,  0, 0   ],
              [0,   0,   0, 0, 0,   0,  0,  0, 0   ],
              
              ])

In [11]:
eVals, eVecs = la.eig(df) 
order = np.absolute(eVals).argsort()[::-1] 
eVals = eVals[order]
eVecs = eVecs[:,order]

df1 = eVecs[:, 0] 
100 * np.real(df1 / np.sum(df1))

array([ 0.00000000e+000,  0.00000000e+000, -9.01875762e-290,
        1.00000000e+002,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000])

In [8]:
df1 = 100 * np.ones(9) / 9
df1


array([11.11111111, 11.11111111, 11.11111111, 11.11111111, 11.11111111,
       11.11111111, 11.11111111, 11.11111111, 11.11111111])

In [9]:
df1 = df @ df1 
df1

array([ 0.        , 11.11111111, 11.11111111, 77.77777778, 11.11111111,
        0.        ,  0.        ,  0.        ,  0.        ])

In [17]:
#trying convergence

df1_old=df1
df1= df @ df1

i=0
while la.norm(df1_old - df1)>0.01:
    df1_old=df1
    df1= df @ df1
    i=i+1
  
print("number of convergences")
i 

df1

number of convergences


array([0., 0., 0., 0., 0., 0., 0., 0., 0.])